title: Banyu V. # your name (or website title) here
logo: "/images/BV Prof pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  A data-driven generalist with investment banking and consumer-tech background.
  <br><br>
  I have deep interest in big data problems involving Data Science, Machine Learning, and Econometrics.
  <br><br>
  Currently working in Lazada focusing on the growth, marketing, and strategy.
  <br><br>
  <a href="https://www.linkedin.com/in/banyuvidiapratama/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal


colors:
  crimson: '#900C3F'
