title: Banyu V. # your name (or website title) here
logo: "/images/BV Prof pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data-driven generalist with inter-disciplinary exposures from analytics, investment, to real-sector ecosystem. 
  <br><br>
  I have deep interest in research particularly in big data problems involving Data Science, Machine Learning, Statistics and Data Visualisation.
  <br><br>
  Currently leading a team in the user growth function in Lazada focusing on the growth, marketing and strategy.
  <br><br>
  <a href="https://www.linkedin.com/in/banyuvidiapratama/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
