title: Banyu V. # your name (or website title) here
logo: "/images/BV Prof pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data-driven generalist with inter-disciplinary exposures from investment banking, portfolio management, to operation ecosystem. 
  <br><br>
  Currently leading a team in the user growth function in Lazada focusing on the growth, marketing, strategy, and business operations. Previously at Grab, CapAsia Private Equity, and CIMB Investment Banking. 
  <br><br>
  <a href="https://www.linkedin.com/in/banyuvidiapratama/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
